#!/bin/bash
set -xeuo pipefail

testctl get

#export KUBECONFIG=$(pwd)/kubeconfig
#for X in *; do
#    ./testctl-rsync.sh $X /root/
#done
#
#./testctl-ssh.sh -- terraform init
#./testctl-ssh.sh -- terraform apply -auto-approve
