name: Kubeflow + MLFlow - Combinator Stack
base:
  kernel_image: quay.io/testfaster/ignite-kernel
  os_dockerfile: |-
    # This dockerfile defines the base disk image for your VMs
    FROM quay.io/testfaster/kube-ubuntu
    RUN apt update
    RUN apt install gnupg2 software-properties-common rsync -y
    RUN curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
    RUN apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    RUN apt install terraform -y
  preload_docker_images:
    - aipipeline/kubeflow-operator:v1.2.0
    - argoproj/argoui:v2.3.0
    - argoproj/workflow-controller:v2.3.0
    - bitnami/mysql:8.0.22-debian-10-r23
    - gcr.io/arrikto/dexidp/dex:4bede5eb80822fc3a7fc9edca0ed2605cd339d17
    - gcr.io/arrikto/kubeflow/oidc-authservice:28c59ef
    - gcr.io/google_containers/spartakus-amd64:v1.1.0
    - gcr.io/k8s-minikube/storage-provisioner:v1.8.1
    - gcr.io/kfserving/kfserving-controller:v0.3.0
    - gcr.io/knative-releases/knative.dev/serving/cmd/activator
    - gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler-hpa
    - gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler
    - gcr.io/knative-releases/knative.dev/serving/cmd/controller
    - gcr.io/knative-releases/knative.dev/serving/cmd/networking/istio
    - gcr.io/knative-releases/knative.dev/serving/cmd/webhook
    - gcr.io/kubebuilder/kube-rbac-proxy:v0.4.0
    - gcr.io/kubeflow-images-public/admission-webhook:vmaster-gaf96e4e3
    - gcr.io/kubeflow-images-public/centraldashboard:v1.1.0-g35d7484a
    - gcr.io/kubeflow-images-public/jupyter-web-app:vmaster-gd9be4b9e
    - gcr.io/kubeflow-images-public/katib/v1alpha3/katib-controller:917164a
    - gcr.io/kubeflow-images-public/katib/v1alpha3/katib-db-manager:917164a
    - gcr.io/kubeflow-images-public/katib/v1alpha3/katib-ui:917164a
    - gcr.io/kubeflow-images-public/kfam:vmaster-gf3e09203
    - gcr.io/kubeflow-images-public/kubernetes-sigs/application:1.0-beta
    - gcr.io/kubeflow-images-public/metadata-frontend:v0.1.8
    - gcr.io/kubeflow-images-public/metadata:v0.1.11
    - gcr.io/kubeflow-images-public/notebook-controller:vmaster-gf39279c0
    - gcr.io/kubeflow-images-public/profile-controller:vmaster-ga49f658f
    - gcr.io/kubeflow-images-public/pytorch-operator:vmaster-gd596e904
    - gcr.io/kubeflow-images-public/tf_operator:vmaster-ga2ae7bff
    - gcr.io/ml-pipeline/api-server:0.2.5
    - gcr.io/ml-pipeline/envoy:metadata-grpc
    - gcr.io/ml-pipeline/frontend:0.2.5
    - gcr.io/ml-pipeline/persistenceagent:0.2.5
    - gcr.io/ml-pipeline/scheduledworkflow:0.2.5
    - gcr.io/ml-pipeline/viewer-crd-controller:0.2.5
    - gcr.io/ml-pipeline/visualization-server:0.2.5
    - gcr.io/spark-operator/spark-operator:v1beta2-1.1.0-2.4.5
    - gcr.io/tfx-oss-public/ml_metadata_store_server:v0.21.1
    - ghcr.io/combinator-ml/mlflow:1.18.0
    - grafana/grafana:6.7.4
    - istio/operator:1.6.8
    - istio/pilot:1.6.8
    - istio/proxyv2:1.6.8
    - jaegertracing/all-in-one:1.16
    - k8s.gcr.io/coredns:1.6.5
    - k8s.gcr.io/etcd:3.4.3-0
    - k8s.gcr.io/kube-apiserver:v1.17.11
    - k8s.gcr.io/kube-controller-manager:v1.17.11
    - k8s.gcr.io/kube-proxy:v1.17.11
    - k8s.gcr.io/kube-scheduler:v1.17.11
    - k8s.gcr.io/pause:3.1
    - minio/mc:RELEASE.2020-11-25T23-04-07Z
    - minio/minio:RELEASE.2018-02-09T22-40-05Z
    - minio/minio:RELEASE.2020-12-03T05-49-24Z
    - mysql:5.6
    - mysql:8
    - mysql:8.0.3
    - prom/prometheus:v2.15.1
    - quay.io/jetstack/cert-manager-cainjector:v0.16.1
    - quay.io/jetstack/cert-manager-controller:v0.16.1
    - quay.io/jetstack/cert-manager-webhook:v0.16.1
    - quay.io/kiali/kiali:v1.18
    - seldonio/seldon-core-operator:1.2.1
    - tensorflow/tensorflow:1.8.0
  prewarm_script: |-
    #!/bin/bash
    set -euo pipefail
    echo "bump cache 1"
    git clone https://github.com/combinator-ml/terraform-k8s-stack-kubeflow-mlflow repo
    cd repo
    git checkout 7dc9f2ce377b2224641e7ca078cf8e6271258bf2
    cd examples/testfaster
    terraform init
    KUBE_CONFIG_PATH=~/.kube/config terraform apply -auto-approve

  kubernetes_version: v1.17.11

runtime:
  cpus: 16
  memory: 32GB
  disk: 200GB
prewarm_pool_size: 4
max_pool_size: 24
default_lease_timeout: "1h"
pool_sleep_timeout: "1w"
shared: true

launch:
  title: Kubeflow + MLFlow
  buttons:
    - title: Kubeflow
      port: 31380
    - title: MLFlow
      port: 30600
    - title: Minio
      port: 30650
  homepage: |
    ## Instructions
    Click the button to launch the UIs.

    Kubeflow is big, so it can take some time to start. If it 404's, wait for a while, then refresh.

    Once you see the login screen, the username is admin@kubeflow.org and the password is 12341234
