dependencies:

  - name: kube-state-metrics
    version: "2.7.*"
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: kubeStateMetrics.enabled

  - name: grafana
    version: "5.6.12"
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
